apiVersion: v2
name: platform-mesh-operator
description: A Helm chart to automate bootstrapping of new environment
type: application
version: 0.34.0
appVersion: "v0.80.0"
dependencies:
  - name: common
    version: 0.13.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: platform-mesh-operator-crds
    version: 0.9.1
    repository: oci://ghcr.io/platform-mesh/helm-charts
    condition: crds.enabled
