{{ include "kcp.etcd" (dict "name" (.Values.kcp.etcd.name | default "etcd-kcp-client") "namespace" (.Values.kcp.namespace | default "kcp-system") "etcd" .Values.kcp.etcd) }}
---
apiVersion: operator.kcp.io/v1alpha1
kind: RootShard
metadata:
  name: root
  namespace: {{ .Values.kcp.namespace | default "kcp-system" }}
spec:
{{- include "kcp.shard.spec" (dict "root" $ "replicas" .Values.kcp.rootShard.replicas "shardBaseURL" .Values.kcp.rootShard.shardBaseURL "extraArgs" .Values.kcp.rootShard.extraArgs "resources" .Values.kcp.rootShard.resources "hostname" .Values.kcp.external.hostname "port" .Values.kcp.external.port "webhookPort" .Values.kcp.webhook.port) | nindent 2 }}
  certificates:
    issuerRef:
      group: cert-manager.io
      kind: Issuer
      name: selfsigned
  cache:
    embedded:
      enabled: true
  etcd:
    endpoints:
      - http://{{ .Values.kcp.etcd.service.name}}.{{ .Values.kcp.namespace}}.svc.cluster.local:{{.Values.kcp.etcd.service.port}}
  certificateTemplates:
    server:
      spec:
        dnsNames:
          - root-kcp
          - root-kcp.{{ .Values.kcp.namespace | default "kcp-system" }}
          - root-kcp.{{ .Values.kcp.namespace | default "kcp-system" }}.svc.cluster.local
          - root.kcp.localhost
---
{{ include "kcp.tlsroute" (dict "name" "kcp-root-shard-tlsroute" "hostname" "root.kcp.localhost" "serviceName" "root-kcp" "namespace" (.Values.kcp.namespace | default "kcp-system") "gatewayName" .Values.gatewayApi.name) }}
