{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: kcp-front-proxy-tlsroute
  namespace: {{ .Values.kcp.namespace | default "kcp-system" }}
spec:
  hostnames:
  - {{ .Values.kcp.external.hostname }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gatewayApi.name }}
    sectionName: passthrough
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: frontproxy-front-proxy
      namespace: {{ .Values.kcp.namespace | default "kcp-system" }}
      port: 6443
{{- end }}
