apiVersion: v1
kind: Secret
metadata:
  name: platform-mesh-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: platform-mesh-cluster
  server: https://${RUNTIME_CLUSTER_IP}:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "",
        "certData": "",
        "keyData": ""
      }
    }
