apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ocm-k8s-toolkit
  namespace: default
spec:
  interval: 5m
  url: oci://ghcr.io/open-component-model/kubernetes/controller/chart
  ref:
    tag: "0.12.0"
    digest: sha256:34c6c6708faa53f973ca252f6f013bb9107219ef93c009b26a43541e2cedb9e5
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocm-k8s-toolkit
  namespace: default
spec:
  releaseName: ocm-k8s-toolkit
  interval: 5m
  timeout: 15m
  targetNamespace: ocm-system
  chartRef:
    kind: OCIRepository
    name: ocm-k8s-toolkit
  values:
    manager:
      concurrency:
        resource: 3
