{{- if and .Values.dex.enabled .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex
spec:
  {{- with .Values.dex.gatewayApi.hostnames }}
  hostnames:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gatewayApi.name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.dex.gatewayApi.pathPrefix }}
    {{- if or .Values.dex.gatewayApi.filters .Values.dex.gatewayApi.corsFilters }}
    filters:
    {{- with .Values.dex.gatewayApi.filters }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.dex.gatewayApi.corsFilters }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.dex.service.name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.dex.service.port }}
{{- end }}
