{{- if .Values.clusterAccess.marketplace.enabled }}
apiVersion: gateway.platform-mesh.io/v1alpha1
kind: ClusterAccess
metadata:
  name: marketplace
spec:
  path: {{ .Values.clusterAccess.marketplace.path }}
  introspectionPath: "/clusters/*"
  requestPathTemplate: "/clusters/{clusterTarget}"
  auth:
    kubeconfigSecretRef:
      name: {{ .Values.clusterAccess.marketplace.auth.kubeconfigSecretRef.name }}
      namespace: {{ .Values.clusterAccess.marketplace.auth.kubeconfigSecretRef.namespace | default .Release.Namespace }}
      key: {{ .Values.clusterAccess.marketplace.auth.kubeconfigSecretRef.key }}
{{- end }}
