apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
version: 0.17.1
appVersion: v0.17.45
dependencies:
  - name: common
    version: 0.13.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
