apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
version: 0.15.156
appVersion: v0.16.15
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
