apiVersion: v2
name: iam-service
description: A Helm chart for Kubernetes
version: 0.16.40
appVersion: v0.17.40
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
