apiVersion: v2
name: security-operator
description: A Helm chart for security-operator
type: application
version: 0.29.12
appVersion: "v0.27.21"
dependencies:
  - name: security-operator-crds
    version: 0.4.0
    condition: crds.enabled
    repository: oci://ghcr.io/platform-mesh/helm-charts
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
