{{- if .Values.serviceMonitors.kcp.enabled }}
apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  name: {{ .Values.serviceMonitors.kcp.kubeconfig.name }}
  namespace: {{ .Values.serviceMonitors.kcp.namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  username: {{ .Values.serviceMonitors.kcp.kubeconfig.username }}
  groups:
    {{- toYaml .Values.serviceMonitors.kcp.kubeconfig.groups | nindent 4 }}
  validity: {{ .Values.serviceMonitors.kcp.kubeconfig.validity }}
  secretRef:
    name: {{ .Values.serviceMonitors.kcp.kubeconfig.secretName }}
  target:
    rootShardRef:
      name: root
{{- end }}
