apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Values.otelCollector.name }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  image: {{ .Values.otelCollector.image }}
  mode: {{ .Values.otelCollector.mode }}
  replicas: {{ .Values.otelCollector.replicas }}
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  config:
    receivers:
      prometheus:
        config:
          scrape_configs: []
    processors:
      batch:
        timeout: {{ .Values.otelCollector.config.batchTimeout }}
    exporters:
      prometheusremotewrite:
        endpoint: {{ include "observability.prometheusEndpoint" . }}
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite]
