apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-mesh-system
resources:
  - ocm-signing-public-cert.yaml
  - repository.yaml
  - component.yaml
  - ocm-resolver-config.yaml
