apiVersion: v2
name: terminal-controller-manager
description: A Helm chart to deploy platform-mesh Terminal Controller Manager
type: application
version: 0.3.0
appVersion: "v0.4.1"
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
