apiVersion: delivery.ocm.software/v1alpha1
kind: Component
metadata:
  name: platform-mesh
spec:
  repositoryRef:
    name: platform-mesh
  component: github.com/platform-mesh/platform-mesh
  semver: PLACEHOLDER # Replace with PLATFORM_MESH_VERSION when set
  interval: 1m
  verify:
    # ocm.platform-mesh is for PM <= 0.4.0-build.513
    # - signature: ocm.platform-mesh
    #   secretRef:
    #     name: ocm-signing-public-cert
    # helm-charts.platform-mesh is for PM >= 0.4.0-build.516
    - signature: helm-charts.platform-mesh
      secretRef:
        name: ocm-signing-public-cert
  ocmConfig:
    - kind: Repository
      apiVersion: delivery.ocm.software/v1alpha1
      name: platform-mesh
      namespace: platform-mesh-system
