apiVersion: v1
kind: Secret
metadata:
  name: ocm-signing-public-cert
type: Opaque
stringData:
  ocm.platform-mesh: |
    -----BEGIN CERTIFICATE-----
    MIIDHDCCAgSgAwIBAgIQTBfx4G6QIFoB3EfYaZZfAzANBgkqhkiG9w0BAQsFADAw
    MRYwFAYDVQQKDA1QbGF0Zm9ybSBNZXNoMRYwFAYDVQQDDA1wbGF0Zm9ybS1tZXNo
    MB4XDTI2MDQwOTE0MTg0M1oXDTM2MDQwNjE0MTg0M1owHDEaMBgGA1UEAxMRb2Nt
    LnBsYXRmb3JtLW1lc2gwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDS
    Ng1Ch5HP2BRV2QBxc0rJzgu+1tOqveVKFlZn2WG+zqTo85uEicuUIe9Sg1nt9cf+
    JpX/XIyBhnRSFWofdVTDCXQAnd0s4BgErEYRDEL5AHyLDicTrF32NquU9m0jJ6j3
    wFQ9pd1+JFuL84+Ef545ZvxTm97cxaeNC/mGi1uNF4qF1wZaTNBGt6taB/mJSs5q
    S752SpCzkvzXQ3r49N9tz+NUDo1w64zIhtqnEDABLdvU04hGOWQkvUHwV2Xdluk5
    c8DC5N48I1T2z4EdloAQu3s8Ser9SCGZeST49iFg9V60G+p7nj9hThcYDYXdGQ+g
    jhh7I4Z5a27x4T5BTDgFAgMBAAGjRjBEMBMGA1UdJQQMMAoGCCsGAQUFBwMDMAwG
    A1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUyoPHxtTZ7d3FQyoAPI/Oga9P+KUwDQYJ
    KoZIhvcNAQELBQADggEBAMtZhcGtJsgc3MRfhMGwhYBOKUrnb0GqzOV9wQTlG+DP
    dja16Q+ous0Dv1VfqnW3RyoHHDC6/CpAPF/3muPCoS1CHq0KBrncG5fEFGqNUdpj
    JMWBlgPXvotCx0EnT1dQ2zrXItohTAPdE61FYXJFEPapoXR3HCDrO1+x9xfzWKQt
    USYQEYWleziQPK2WsIyrUQIk+vbfelezm0ZMFaGxWyXxUvIilsKWJMLbNenHtnbG
    jKy9URJ7BhSsD0BHQxP7/RGDgECE3HKNLzGRzL5umizURfzbkbrTAizXnexvn+Y7
    CGmLhO/M52fTVWj1nJRUZ+iZwVRZ91kaYCH+snkKSO8=
    -----END CERTIFICATE-----
