apiVersion: v2
appVersion: "v0.11.11"
description: Helm Chart for the marketplace-ui
name: marketplace-ui
version: 0.6.56
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
