permissions:
  contents: write
  packages: write

name: Build account-operator Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/account-operator/**'
      - '.github/workflows/account-operator.yaml'
      - '.ocm/component-constructor-chart-only.yaml'
  pull_request:
    paths:
      - 'charts/account-operator/**'
      - '.github/workflows/account-operator.yaml'

jobs:
  pipeline:
    concurrency:
      group: account-operator-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: account-operator
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit


