name: DCO
on:
  merge_group:

permissions:
  contents: read

jobs:
  DCO:
    runs-on: ubuntu-latest
    steps:
      - run: echo "DCO app doesn't support merge groups, so this allows them until it does. See https://github.com/dcoapp/app/issues/199"
        shell: bash
