name: Build example-httpbin-operator Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/example-httpbin-operator/**'
      - '.github/workflows/example-httpbin-operator.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

permissions:
  contents: write
  packages: write

jobs:
  pipeline:
    concurrency:
      group: example-httpbin-operator-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: example-httpbin-operator
      componentConstructorFile: .ocm/component-constructor-example-httpbin-operator.yaml
      chartOnly: true
    secrets: inherit

