name: Build iam-ui Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/iam-ui/**'
      - '.github/workflows/iam-ui.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

permissions:
  contents: write
  packages: write

jobs:
  pipeline:
    concurrency:
      group: iam-ui-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: iam-ui
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

