name: Build infra Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/infra/**'
      - '.github/workflows/infra.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

permissions:
  contents: read

jobs:
  pipeline:
    concurrency:
      group: infra-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    permissions:
      contents: write
      packages: write
    with:
      chartFolder: charts
      chartName: infra
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

