name: Trigger OCM Version Update
on:
  workflow_call:

jobs:
  trigger-ocm-version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
         app-id: "1415820"
         private-key: ${{ secrets.PM_PUBLISHER_PRIVATE_KEY }}
         owner: ${{ github.repository_owner }}
         repositories: |
           helm-charts
      - run: gh workflow run ocm-aggregator.yaml --repo platform-mesh/helm-charts
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
