name: Build kcp-mcp-vw Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/kcp-mcp-vw/**'
      - '.github/workflows/kcp-mcp-vw.yaml'
      - '.ocm/component-constructor-chart-only.yaml'
      - '.ocm/component-constructor-service-kcp-mcp-vw.yaml'

permissions:
  contents: read

jobs:
  pipeline:
    concurrency:
      group: kcp-mcp-vw-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    permissions:
      contents: write
      packages: write
    with:
      chartFolder: charts
      chartName: kcp-mcp-vw
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
      serviceComponentConstructorFile: .ocm/component-constructor-service-kcp-mcp-vw.yaml
    secrets: inherit
