permissions:
  contents: write
  packages: write

name: Build kubernetes-graphql-gateway-crds Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/kubernetes-graphql-gateway-crds/**'
      - '.github/workflows/kubernetes-graphql-gateway-crds.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

jobs:
  pipeline:
    concurrency:
      group: kubernetes-graphql-gateway-crds-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: kubernetes-graphql-gateway-crds
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit
