name: Build marketplace-ui Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/marketplace-ui/**'
      - '.github/workflows/marketplace-ui.yaml'
      - '.ocm/component-constructor-chart-only.yaml'
  pull_request:
    paths:
      - 'charts/marketplace-ui/**'
      - '.github/workflows/marketplace-ui.yaml'

permissions:
  contents: write
  packages: write

jobs:
  pipeline:
    concurrency:
      group: marketplace-ui-${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-chart.yml@main
    with:
      chartFolder: charts
      chartName: marketplace-ui
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

