name: OpenSSF Scorecard
on:
    push:
        branches: [main]
    schedule:
        - cron: '30 4 * * 1'
    workflow_dispatch:

permissions: read-all

jobs:
    scorecard:
        uses: platform-mesh/.github/.github/workflows/job-ossf-scorecard.yml@main
        permissions:
            security-events: write
            id-token: write
            contents: read
            actions: read
