name: Build portal Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/portal/**'
      - '.github/workflows/portal.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

permissions:
  contents: write
  packages: write
jobs:
  pipeline:
    concurrency:
      group: portal-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: portal
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit
