permissions:
  contents: write
  packages: write
name: Build rebac-authz-webhook Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/rebac-authz-webhook/**'
      - '.github/workflows/rebac-authz-webhook.yaml'
      - '.ocm/component-constructor-chart-only.yaml'
  pull_request:
    paths:
      - 'charts/rebac-authz-webhook/**'
      - '.github/workflows/rebac-authz-webhook.yaml'

jobs:
  pipeline:
    concurrency:
      group: rebac-authz-webhook-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: rebac-authz-webhook
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

