name: Build security-operator Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/security-operator/**'
      - '.github/workflows/security-operator.yaml'
      - '.ocm/component-constructor.yaml'
  pull_request:
    paths:
      - 'charts/security-operator/**'
      - '.github/workflows/security-operator.yaml'

jobs:
  pipeline:
    concurrency:
      group: security-operator-${{ github.ref }}
      cancel-in-progress: true
    uses: platform-mesh/.github/.github/workflows/pipeline-chart.yml@74406045a622c7b7018b222b0fc58c0090bc9d86 # main
    with:
      chartFolder: charts
      chartName: security-operator
      additionalTestFilesCommand: ''
      chartRepos: 'bitnami=https://charts.bitnami.com/bitnami,openfga=https://openfga.github.io/helm-charts'
    secrets: inherit

