permissions:
  contents: write
  packages: write

name: Build security-operator Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/security-operator/**'
      - '.github/workflows/security-operator.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

jobs:
  pipeline:
    concurrency:
      group: security-operator-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    with:
      chartFolder: charts
      chartName: security-operator
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

