name: Build terminal-controller-manager Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'charts/terminal-controller-manager/**'
      - '.github/workflows/terminal-controller-manager.yaml'
      - '.ocm/component-constructor-chart-only.yaml'

permissions:
  contents: read

jobs:
  pipeline:
    concurrency:
      group: terminal-controller-manager-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/pipeline-chart.yml
    permissions:
      contents: write
      packages: write
    with:
      chartFolder: charts
      chartName: terminal-controller-manager
      componentConstructorFile: .ocm/component-constructor-chart-only.yaml
      chartOnly: true
    secrets: inherit

