{{- if .Values.keycloak.operator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.operator.admin.username | quote }}
  password: {{ .Values.keycloak.operator.admin.password | quote }}
  secret: {{ .Values.keycloak.operator.admin.secret | quote }}
{{- end }}
