{{- if .Values.keycloak.operator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.operator.db.username | quote }}
  password: {{ .Values.keycloak.operator.db.password | quote }}
{{- end }}
