{{- if .Values.rbac.enabled }}
{{- $provider := .Values.listener.provider | default "multi" }}
{{- if or (not .Values.kcp.enabled) (eq $provider "single") (eq $provider "multi") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.entity.name" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.entity.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "common.entity.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
