apiVersion: v2
name: virtual-workspaces
description: A Helm chart to deploy platform-mesh virtual-workspaces
type: application
version: 0.3.8
appVersion: "v0.10.6"
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
