apiVersion: v2
name: virtual-workspaces
description: A Helm chart to deploy platform-mesh virtual-workspaces
type: application
version: 0.3.7
appVersion: "v0.8.26"
dependencies:
  - name: common
    version: 0.12.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
