apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/platform-mesh-operator
  - rbac.yaml
  - ../../components/ocm

patches:
  - target:
      kind: Component
      name: platform-mesh
    patch: |
      - op: add
        path: /metadata/namespace
        value: platform-mesh-system
      - op: replace
        path: /spec/ocmConfig/0/namespace
        value: platform-mesh-system
  - target:
      kind: Repository
      name: platform-mesh
    patch: |
      - op: add
        path: /metadata/namespace
        value: platform-mesh-system
  - target:
      kind: Secret
      name: ocm-signing-public-cert
    patch: |
      - op: add
        path: /metadata/namespace
        value: platform-mesh-system
  - target:
      kind: PlatformMeshOperator
      name: platform-mesh-operator
    patch: |
      - op: add
        path: /spec/remoteRuntimeEnabled
        value: "true"
      - op: add
        path: /spec/remoteRuntimeSecretName
        value: platform-mesh-kubeconfig
      - op: add
        path: /spec/remoteRuntimeSecretKey
        value: kubeconfig
      - op: add
        path: /spec/kcpUrl
        value: https://root.kcp.localhost:8443
      - op: add
        path: /spec/runtimeClusterIp
        value: ${RUNTIME_CLUSTER_IP}
