image:
  # -- The image repository
  name: quay.io/keycloak/keycloak-operator
  # -- The image tag (defaults to appVersion)
  tag: ""

keycloakImage:
  # -- The Keycloak image repository
  repository: ghcr.io/platform-mesh/custom-images/keycloak
  # -- The Keycloak image tag (defaults to appVersion)
  tag: "v26.6.0"

# -- Namespace to watch for Keycloak CRs. Defaults to the release namespace.
watchNamespaces: ""

deployment:
  replicas: 1
  specTemplate:
    # -- Annotations for the pod template
    annotations: {}
    # -- Labels for the pod template
    labels: {}
  resources:
    limits:
      # -- Memory limit
      memory: "450Mi"
      # -- CPU limit
      cpu: "700m"
    requests:
      # -- CPU request
      cpu: "300m"
      # -- Memory request
      memory: "450Mi"
