image:
  # -- The image repository
  name: ghcr.io/platform-mesh/account-operator
  # Overwrite image.tag to use a different image tag then .chart.appVersion
  #  tag: latest

crds:
  # -- Enable CRDs
  enabled: true

webhooks:
  # -- Enable webhooks
  enabled: true

  # -- Register webhooks, flag to toggle if webhooks should be registered on the runtime cluster
  register: false
  # -- The directory for webhook certificates
  certDir: /certs
  # -- List of denied organization names
  denyList: ["admin", "root", "system", "www"]
  additionalAccountTypes: ["account"]

  # -- CA certificate duration (default: 1 year)
  caDuration: 8760h
  # -- CA certificate renewal time before expiration (default: 30 days)
  caRenewBefore: 720h
  # -- Serving certificate duration (default: 3 months)
  certDuration: 2160h
  # -- Serving certificate renewal time before expiration (default: 30 days)
  certRenewBefore: 720h

# -- The kcp configuration
kcp:
  # -- Enable kcp
  enabled: false
  # -- The URL for the virtual workspace
  virtualWorkspaceUrl: ""
  # -- kcp APIExportEndpointSliceName
  apiExportEndpointSliceName: "core.platform-mesh.io"

subroutines:
  workspaceType:
    # -- Enable workspace type subroutine
    enabled: true
  accountInfo:
    # -- Enable AccountInfo subroutine
    enabled: true
  workspace:
    # -- Enable workspace subroutine
    enabled: true
  workspaceReady:
    # -- Enable workspace ready subroutine
    enabled: true

controllers:
  accountInfo:
    # -- Enable AccountInfo controller
    enabled: true

# -- The secret for kubeconfig
kubeconfigSecret: ""

security:
  # -- Mount the service account token
  mountServiceAccountToken: true

deployment:
  specTemplate:
    # -- The annotations for the deployment
    annotations: {}
    # -- The labels for the deployment
    labels: {}
  replicas: 1

hostAliases:
  enabled: false

operator:
  leaderElect: true

istio:
  enabled: false
