apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-mesh-profile
  namespace: platform-mesh-system
data:
  profile.yaml: |
    infra:
      deploymentTechnology: fluxcd
      ocm:
        component:
          name: platform-mesh
        interval: 3m
        referencePath: []
        repo:
          name: platform-mesh
        skipVerify: true
      certManager:
        enabled: true
        interval: 1m
        name: cert-manager
        ocmResourceName: chart
        targetNamespace: default
        values:
          installCRDs: true
      gatewayApi:
        syncOptions:
        - ServerSideApply=true
        - SkipCRDs=false
        enabled: true
        kustomization:
          install:
            crds: Skip
          interval: 1m
          path: ./config/crd/experimental
        name: gateway-api
        ocmResourceName: crds
      traefik:
        skipCrds: true
        syncOptions:
        - SkipCRDs=true
        syncWave: 1
        chart:
          name: traefik
        enabled: true
        interval: 1m
        name: traefik
        ocmResourceName: chart
        targetNamespace: default
        values:
          experimental:
            kubernetesGateway:
              enabled: true
          gateway:
            enabled: false
          gatewayClass:
            enabled: true
          ports:
            websecure:
              exposedPort: 8443
              nodePort: 31000
          providers:
            kubernetesGateway:
              enabled: true
              experimentalChannel: true
          service:
            spec:
              clusterIP: 10.96.188.4
            type: NodePort
      etcdDruid:
        enabled: true
        interval: 1m
        name: etcd-druid
        ocmResourceName: etcd-druid
        ocmImageResourceName: image
        targetNamespace: etcd-druid-system
        values: {}
      traefikCRDs:
        chart:
          name: traefik-crds
        enabled: true
        interval: 1m
        name: traefik-crds
        ocmComponentName: traefik
        ocmResourceName: crds
        targetNamespace: default
        values:
          gatewayAPI: false
    components:
      deploymentTechnology: fluxcd
      ocm:
        component:
          create: true
          name: platform-mesh
        interval: 3m
        referencePath: []
        repo:
          create: true
          name: platform-mesh
        skipVerify: true
      services:
        account-operator:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: account-operator
          syncWave: 4
          enabled: true
          values:
            hostAliases:
              enabled: true
            crds:
              enabled: false
            kcp:
              apiExportEndpointSliceName: "core.platform-mesh.io"
            kubeconfigSecret: account-operator-kubeconfig
            log:
              level: debug
              noJson: true
            subroutines:
              fga:
                grpcAddr: openfga:8081
            tracing:
              collector:
                host: observability-opentelemetry-collector.observability.svc.cluster.local:4317
              enabled: false
        extension-manager-operator:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: extension-manager-operator
          syncWave: 4
          enabled: true
          values:
            crds:
              enabled: false
            hostAliases:
              enabled: true
            kcp:
              enabled: true
              kubeconfigSecret: extension-manager-operator-kubeconfig
            tracing:
              collector:
                host: observability-opentelemetry-collector.observability.svc.cluster.local:4317
              enabled: false
        infra:
          enabled: true
          imageResources: [] # Disable kcp-image OCM Resource to allow custom kcp.image.tag
          dependsOn:
          - name: keycloak-operator
            namespace: platform-mesh-system
          - name: cnpg-operator
            namespace: platform-mesh-system
          values:
            cnpg:
              enabled: true
            cors:
              enabled: true
            gatewayApi:
              enabled: true
            hostAliases:
              enabled: true
            keycloak:
              operator:
                hostname: https://portal.localhost:8443/keycloak/
                enabled: true
                health:
                  port: 9000
                  periodSeconds: 10
                  liveness:
                    path: /keycloak/health/live
                    failureThreshold: 3
                  readiness:
                    path: /keycloak/health/ready
                    initialDelaySeconds: 0
                    periodSeconds: 10
                  startup:
                    path: /keycloak/health
                    failureThreshold: 600
              service:
                name: keycloak-service
                port: 8080
              keycloakConfig:
                url: http://keycloak-service.platform-mesh-system.svc.cluster.local:8080/keycloak
            kcp:
              auth:
                serviceAccount:
                  enabled: true
              frontProxy:
                clusterIP: 10.96.0.100
                port: 8443
              image:
                tag: v0.31.0
              rootShard:
                extraArgs:
                - --feature-gates=WorkspaceAuthentication=true
              shards: []
              webhook:
                enabled: true
            traefik:
              accessControlAllowOriginList:
              - http://localhost:4200
              - http://localhost:4300
              - http://*.localhost:4200
              - http://*.localhost:4300
              - http://sub.localhost:4300
              - https://portal.localhost:8443
              - https://*.portal.localhost:8443
        iam-ui:
          enabled: true
          syncWave: 4
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: iam-ui
        iam-service:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: iam-service
          syncWave: 4
          enabled: true
          values:
            caSecret: domain-certificate-ca
            extraArgs:
            - --no-json
            cors:
              enabled: true
            hostAliases:
              enabled: true
        init-agent:
          helmRepo: true
          absoluteReferencePath:
          - name: init-agent
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: init-agent
            absoluteReferencePath:
            - name: init-agent
          syncWave: 4
          enabled: true
          values:
            configWorkspace: root:platform-mesh-system
            kcpKubeconfig: init-agent-kubeconfig
            replicas: 1
            leaderElection:
              enabled: false
            hostAliases:
              enabled: true
              values:
                - ip: "10.96.188.4"
                  hostnames:
                    - "localhost"
        kcp:
          external: true
        kcp-operator:
          syncWave: 1
          external: true
          enabled: true
          helmRepo: true
          targetNamespace: kcp-operator
        keycloak-operator:
          enabled: true
          external: true
          absoluteReferencePath:
            - name: keycloak-operator
            - name: chart
          values:
            watchNamespaces: platform-mesh-system
        cnpg-operator:
          enabled: true
          external: true
          targetNamespace: platform-mesh-system
          absoluteReferencePath:
          - name: cnpg-operator
        kubernetes-graphql-gateway:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: kubernetes-graphql-gateway
          syncWave: 4
          enabled: true
          values:
            gatewayApi:
              enabled: true
            hostAliases:
              enabled: true
            istio:
              enabled: false
            kubeConfig:
              enabled: true
              secretName: kubernetes-graphql-gateway-kubeconfig
            listener:
              virtualWorkspacesConfig:
                content:
                  virtualWorkspaces:
                  - kubeconfig: /app/kubeconfig/kubeconfig
                    name: contentconfigurations
                    url: https://frontproxy-front-proxy.platform-mesh-system:8443/services/contentconfigurations
                  - kubeconfig: /app/kubeconfig/kubeconfig
                    name: marketplace
                    url: https://frontproxy-front-proxy.platform-mesh-system:8443/services/marketplace
                enabled: true
            tracing:
              enabled: false
            trust:
              default:
                audience: default
                jwksUrl: http://keycloak-headless.platform-mesh-system:8080/keycloak/realms/default/protocol/openid-connect/certs
                trustedIssuer: 'https://{{ .baseDomainPort }}/keycloak/realms/default'
        observability:
          syncWave: 4
          enabled: false
          targetNamespace: observability
        openfga:
          enabled: true
          external: true
          syncWave: 2
          helmRepo: true
          suspend: true
          imageResources:
          - name: openfga-image
            annotations:
              repo: oci
              artifact: image
              for: openfga
          - name: openfga-postgresql-image
            resource: postgresql-image
            resourceName: postgresql-image
            annotations:
              repo: oci
              artifact: image
              for: openfga
              path: postgresql.image.tag
              unsuspend: "true"
          values:
            autoscaling:
              enabled: false
            checkQueryCache:
              enabled: true
              limit: 10000
              ttl: 10s
            datastore:
              applyMigrations: true
              engine: postgres
              maxOpenConns: 30
              migrationType: initContainer
              migrations:
                image:
                  pullPolicy: Always
                  repository: groundnuty/k8s-wait-for
                  tag: v2.0
              uri: postgres://postgres:password@openfga-postgres.platform-mesh-system.svc.cluster.local:5432/postgres?sslmode=disable
            extraEnvVars:
            - name: OPENFGA_EXPERIMENTALS
              value: enable-list-users
            image:
              tag: v1.11.2
            log:
              level: info
            migrate:
              repository: openfga/openfga
              annotations:
                sidecar.istio.io/inject: "false"
            podAnnotations:
              traffic.sidecar.istio.io/excludeInboundPorts: "2112"
            postgresql:
              enabled: true
              auth:
                password: password
              image:
                registry: ghcr.io/platform-mesh
                repository: upstream-images/postgresql
                tag: 17.6.0-debian-12-r4
              nameOverride: postgres
            replicaCount: 1
            telemetry:
              trace:
                enabled: true
                otlp:
                  endpoint: observability-opentelemetry-collector.openmfp-observability.svc.cluster.local:4317
                  tls:
                    enabled: false
        portal:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: portal
          syncWave: 4
          enabled: true
          values:
            auth:
              default:
                baseDomain: '{{ .baseDomain }}'
                clientId: welcome
                clientSecretKey: attribute.client_secret
                clientSecretName: portal-client-secret-welcome
                discoveryUrl: 'https://{{ .baseDomainPort }}/keycloak/realms/${org-name}/.well-known/openid-configuration'
            cookieDomain: '{{ .baseDomain }}'
            crdGatewayApiUrl: 'https://${org-subdomain}{{ .baseDomain }}/api/kubernetes-graphql-gateway/root:orgs:${org-name}/graphql'
            environment: kind
            extraEnvVars:
            - name: OPENMFP_PORTAL_CONTEXT_IAM_SERVICE_API_URL
              value: https://${org-subdomain}portal.localhost:8443/iam/graphql
            - name: OPENMFP_PORTAL_CONTEXT_CRD_GATEWAY_API_URL
              value: https://${org-subdomain}portal.localhost:8443/gateway/api/clusters/root:orgs:${org-name}/graphql
            - name: NODE_EXTRA_CA_CERTS
              value: /etc/ssl/certs/domain-ca.crt
            extraVolumes:
            - name: domain-ca
              secret:
                secretName: domain-certificate-ca
            extraVolumeMounts:
            - name: domain-ca
              mountPath: /etc/ssl/certs/domain-ca.crt
              subPath: tls.crt
              readOnly: true
            frontendPort: '8443'
            gatewayApi:
              enabled: true
              httpRoute:
                parentRefs:
                - name: k8sapi-gateway
                  kind: Gateway
            hostAliases:
              enabled: true
              entries:
              - ip: "10.96.188.4"
                hostnames:
                - "localhost"
                - "portal.localhost"
                - "kcp.localhost"
                - "root.kcp.localhost"
                - "nereus.kcp.localhost"
                - "triton.kcp.localhost"
            http:
              protocol: https
            kcp:
              kubeconfigSecret: portal-kubeconfig
        rebac-authz-webhook:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: rebac-authz-webhook
          syncWave: 4
          enabled: true
          values:
            hostAliases:
              enabled: true
            certManager:
              createCA: true
              enabled: true
            istio:
              dnsNames:
              - rebac-authz-webhook.platform-mesh-system.svc.cluster.local
              exposed: false
            log:
              level: debug
            openfga:
              url: openfga:8081
        security-operator:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: security-operator
          syncWave: 4
          enabled: true
          values:
            baseDomain: '{{ .baseDomainPort }}'
            caSecret: domain-certificate-ca
            crds:
              enabled: false
            fga:
              extraArgs:
                - --idp-smtp-server=mailpit.platform-mesh-system.svc.cluster.local
                - --idp-smtp-port=1025
                - --idp-from-address=keycloak@portal.localhost
                - --set-default-password
                - --idp-registration-allowed
                - --domain-ca-lookup
                - --development-allow-unverified-emails
                - --idp-additional-redirect-urls=http://localhost:8000/callback*,http://localhost:4300/callback*,http://sub.localhost:4300/callback*
              inviteKeycloakBaseUrl: 'https://{{ .baseDomainPort }}/keycloak'
              target: openfga.platform-mesh-system.svc.cluster.local:8081
            hostAliases:
              enabled: true
            initializer:
              kubeconfigSecret: security-initializer-kubeconfig
              extraArgs:
                - --domain-ca-lookup
                - --idp-smtp-server=mailpit.platform-mesh-system.svc.cluster.local
                - --idp-smtp-port=1025
                - --idp-from-address=keycloak@portal.localhost
                - --development-allow-unverified-emails
                - --idp-additional-redirect-urls=http://localhost:8000/callback*,http://localhost:4300/callback*,http://sub.localhost:4300/callback*
                - --idp-registration-allowed
            kubeconfigSecret: security-operator-kubeconfig
            log:
              level: debug
              noJson: true
            operator:
              maxConcurrentReconciles: 1
              shutdownTimeout: 1m
            system:
              extraArgs:
              - --idp-smtp-server=mailpit.platform-mesh-system.svc.cluster.local
              - --idp-smtp-port=1025
              - --idp-from-address=keycloak@portal.localhost
              - --set-default-password
              - --idp-registration-allowed
            terminator:
              kubeconfigSecret: security-terminator-kubeconfig
        terminal-controller-manager:
          enabled: false
        virtual-workspaces:
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: virtual-workspaces
          syncWave: 4
          enabled: true
          targetNamespace: platform-mesh-system
          values:
            virtualWorkspaceSecretName: virtual-workspaces-cert
            deployment:
              serverUrl: https://frontproxy-front-proxy.platform-mesh-system:8443
              resourceSchemaName: "v250704-6d57f16.contentconfigurations.ui.platform-mesh.io"
              resourceSchemaWorkspace: "root:platform-mesh-system"
        marketplace-ui:
          enabled: true
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: marketplace-ui
          values:
            gatewayApi:
              enabled: true
            istio:
              enabled: false
        terminal-controller-manager:
          enabled: false
          imageResources:
          - annotations:
              repo: oci
              artifact: image
              for: terminal-controller-manager
          - name: terminal-image
            annotations:
              path: terminal.image.tag
              for: terminal-controller-manager
              repo: oci
              artifact: image
            resource: terminal-image
            referencePath:
            - name: terminal-controller-manager
          values:
            kcp:
              kubeconfigSecret: terminal-controller-manager-kubeconfig
        observability:
          syncWave: 4
          enabled: false
          targetNamespace: observability
          values:
            opentelemetry-operator:
              manager:
                collectorImage:
                  repository: otel/opentelemetry-collector-contrib
            prometheus:
              server:
                persistentVolume:
                  enabled: false
                extraFlags:
                - web.enable-remote-write-receiver
              alertmanager:
                enabled: false
              prometheus-node-exporter:
                enabled: false
              prometheus-pushgateway:
                enabled: false
              kube-state-metrics:
                enabled: false
      targetNamespace: platform-mesh-system
