apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../platform-mesh-resource
patches:
  - target:
      kind: PlatformMesh
      name: platform-mesh
    patch: |
      - op: remove
        path: /spec/values/infra/values/kcp/shards
