apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../platform-mesh-resource
patches:
  - target:
      kind: PlatformMesh
      name: platform-mesh
      namespace: platform-mesh-system
    patch: |-
      - op: add
        path: /spec/values
        value:
          services:
            infra:
              values:
                kcp:
                # TODO remove commit image tag when released version is compatible
                  image:
                    tag: "15923aca7"
                  shards:
                    - name: nereus
                    - name: triton