apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.entity.name" . }}
spec:
  image: {{ .Values.image.name }}:{{ .Values.image.tag  }}
  {{- include "common.deploymentBasics" . | nindent 2 }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        {{- include "common.labelMatcher" . | nindent 8 }}
        {{- with .Values.deployment.specTemplate.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deployment.specTemplate.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.imagePullSecret" . | nindent 6 }}
      {{- include "common.pod.securityContext" . | nindent 6 }}
      terminationGracePeriodSeconds: {{ include "common.terminationGracePeriodSeconds" . }}
      containers:
        - {{- include "common.podBasics" . | nindent 10 }}
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELATED_IMAGE_KEYCLOAK
              value: {{ include "keycloak-operator.keycloakImage" . }}
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKREALMIMPORTCONTROLLER_NAMESPACES
              value: {{ .Values.watchNamespaces | default "JOSDK_WATCH_CURRENT" }}
            - name: QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES
              value: {{ .Values.watchNamespaces | default "JOSDK_WATCH_CURRENT" }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
