apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.entity.name" . }}
spec:
  {{- include "common.serviceBasics" . | nindent 2 }}
  ports:
    {{- include "common.servicePorts" . | nindent 4 }}
