apiVersion: core.platform-mesh.io/v1alpha1
kind: PlatformMesh
metadata:
  name: platform-mesh
  namespace: platform-mesh-system
spec:
  exposure:
    port: 8443
    baseDomain: "portal.localhost"
    protocol: "https"
  ocm:
    repo:
      name: platform-mesh
    component:
      name: platform-mesh
    referencePath: []
  featureToggles:
  - name: feature-enable-getting-started
  - name: feature-disable-email-verification
  - name: feature-accounts-in-accounts
  kcp: {}
