apiVersion: v2
appVersion: "v0.11.14"
description: Helm Chart for the iam-ui
name: iam-ui
version: 0.6.17
dependencies:
  - name: common
    version: 0.12.2
    repository: oci://ghcr.io/platform-mesh/helm-charts
