apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../platform-mesh-resource-prerelease
patches:
  - target:
      kind: PlatformMesh
      name: platform-mesh
      namespace: platform-mesh-system
    patch: |-
      - op: add
        path: /spec/values
        value:
          services:
            infra:
              values:
                kcp:
                  external:
                    hostname: kcp.api.{{ .baseDomain }}
                  shards:
                    - name: triton
                      hostname: triton.kcp.{{ .baseDomain }}
#                   - name: nereus
#                     hostname: nereus.kcp.{{ .baseDomain }}
