{{- if .Values.providers.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.entity.name" . }}-providers
  namespace: {{ .Release.Namespace }}
{{- include "common.imagePullSecret" . }}
{{- end }}
